/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module example;

static import example_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;


void My_variable(double value) @property {
  example_im.My_variable_set(value);
}

double My_variable() @property {
  auto ret = example_im.My_variable_get();
  return ret;
}

int fact(int n) {
  auto ret = example_im.fact(n);
  return ret;
}

int my_mod(int x, int y) {
  auto ret = example_im.my_mod(x, y);
  return ret;
}

string get_time() {
  string ret = std.conv.to!string(example_im.get_time());
  return ret;
}

SWIGTYPE_p_std__vectorT_std__string_t get_words() {
  SWIGTYPE_p_std__vectorT_std__string_t ret = new SWIGTYPE_p_std__vectorT_std__string_t(example_im.get_words(), true);
  return ret;
}

class SWIGTYPE_p_std__vectorT_std__string_t {
  private void* swigCPtr;

  public this(void* cObject, bool futureUse) {
    swigCPtr = cObject;
  }

  protected this() {
    swigCPtr = null;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin example_im.SwigOperatorDefinitions;
}
