/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_omscript_WRAP_H_
#define SWIG_omscript_WRAP_H_

class SwigDirector_om_callback : public om_callback, public Swig::Director {

public:
    SwigDirector_om_callback();
    virtual ~SwigDirector_om_callback();
    virtual om_data run(om_list_data arg0);

    typedef void * (* SWIG_Callback0_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackrun);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_run;
};


#endif
